accelerate launch --config_file ./config.yaml run.py \
    --mode train \
    --data_dir ./data/raw_data/ \
    --model temdnet \
    --epochs 220 \
    --batch_size 128 \
    --lr 1e-3 \
    --lr_decay 0.98 \
    --lr_step 1 \
    --stddev 0.05 \
    --ckpt_dir ./checkpoints \
